# Define the project configuration
products:
  - kubedoop-base
  - vector
  # devel
  - java-base
  - java-devel
  - go-devel
  # tools
  - krb5
  - tools
  - testing-tools
  # apps
  - airflow
  - superset
  - dolphinscheduler
  - kafka
  - trino
  - zookeeper
  - hadoop
  - hive
  - hbase
  - spark-k8s
  - nifi
# If file under the path is changed, the all product will be rebuilt
global-paths:
  - .github/workflows
  - .github/actions
  - .scripts
